List<List<String>> countryData = [
  ["AE", "UAE"],
  ["AF", "Afghanistan"],
  ["AL", "Albania"],
  ["AM", "Armenia"],
  ["sx", "Netherlands Antilles"], // ["AN", "Netherlands Antilles"],
  ["AO", "Angola"],
  ["AR", "Argentina"],
  ["AU", "Australia"],
  ["AW", "Aruba"],
  ["AZ", "Azerbaijan"],
  ["BA", "Bosnia and Herzegovina"],
  ["BB", "Barbados"],
  ["BD", "Bangladesh"],
  ["BG", "Bulgaria"],
  ["BH", "Bahrain"],
  ["BI", "Burundi"],
  ["BM", "Bermuda"],
  ["BN", "Brunei"],
  ["BO", "Bolivia"],
  ["BR", "Brazil"],
  ["BS", "Bahamas"],
  ["BT", "Bhutan"],
  ["BW", "Botswana"],
  ["BY", "Belarus"],
  ["BZ", "Belize"],
  ["CA", "Canada"],
  ["CD", "Congo (DRC)"],
  ["CH", "Switzerland"],
  ["CL", "Chile"],
  ["CN", "China"],
  ["CO", "Colombia"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba"],
  ["CV", "Cape Verde"],
  ["CZ", "Czech Republic"],
  ["DJ", "Djibouti"],
  ["DK", "Denmark"],
  ["DO", "Dominican Republic"],
  ["DZ", "Algeria"],
  ["EG", "Egypt"],
  ["ER", "Eritrea"],
  ["ET", "Ethiopia"],
  ["EU", "Eurozone countries"], //not working
  ["FJ", "Fiji"],
  ["FK", "Falkland Islands"],
  ["FO", "Faroe Islands"],
  ["GB", "United Kingdom"],
  ["GE", "Georgia"],
  ["GG", "Guernsey"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GM", "Gambia"],
  ["GN", "Guinea"],
  ["GT", "Guatemala"],
  ["GY", "Guyana"],
  ["HK", "Hong Kong"],
  ["HN", "Honduras"],
  ["HR", "Croatia"],
  ["HT", "Haiti"],
  ["HU", "Hungary"],
  ["ID", "Indonesia"],
  ["IL", "Israel"],
  ["IM", "Isle of Man"],
  ["IN", "India"],
  ["IQ", "Iraq"],
  ["IR", "Iran"],
  ["IS", "Iceland"],
  ["JE", "Jersey"],
  ["JM", "Jamaica"],
  ["JO", "Jordan"],
  ["JP", "Japan"],
  ["KE", "Kenya"],
  ["KG", "Kyrgyzstan"],
  ["KH", "Cambodia"],
  ["KI", "Kiribati"],
  ["KM", "Comoros"],
  ["KR", "South Korea"],
  ["KW", "Kuwait"],
  ["KY", "Cayman Islands"],
  ["KZ", "Kazakhstan"],
  ["LA", "Laos"],
  ["LB", "Lebanon"],
  ["LK", "Sri Lanka"],
  ["LR", "Liberia"],
  ["LS", "Lesotho"],
  ["LY", "Libya"],
  ["MA", "Morocco"],
  ["MD", "Moldova"],
  ["MG", "Madagascar"],
  ["MK", "North Macedonia"],
  ["MM", "Myanmar"],
  ["MN", "Mongolia"],
  ["MO", "Macau"],
  ["MR", "Mauritania"],
  ["MU", "Mauritius"],
  ["MV", "Maldives"],
  ["MW", "Malawi"],
  ["MX", "Mexico"],
  ["MY", "Malaysia"],
  ["MZ", "Mozambique"],
  ["NA", "Namibia"],
  ["NG", "Nigeria"],
  ["NI", "Nicaragua"],
  ["NO", "Norway"],
  ["NP", "Nepal"],
  ["NZ", "New Zealand"],
  ["OM", "Oman"],
  ["PA", "Panama"],
  ["PE", "Peru"],
  ["PG", "Papua New Guinea"],
  ["PH", "Philippines"],
  ["PK", "Pakistan"],
  ["PL", "Poland"],
  ["PY", "Paraguay"],
  ["QA", "Qatar"],
  ["RO", "Romania"],
  ["RS", "Serbia"],
  ["RU", "Russia"],
  ["RW", "Rwanda"],
  ["SA", "Saudi Arabia"],
  ["SB", "Solomon Islands"],
  ["SC", "Seychelles"],
  ["SD", "Sudan"],
  ["SE", "Sweden"],
  ["SG", "Singapore"],
  ["SH", "Saint Helena"],
  ["SL", "Sierra Leone"],
  ["SL", "Sierra Leone"],
  ["SO", "Somalia"],
  ["SR", "Suriname"],
  ["SS", "South Sudan"],
  ["ST", "São Tomé and Príncipe"],
  ["SY", "Syria"],
  ["SZ", "Eswatini"],
  ["TH", "Thailand"],
  ["TJ", "Tajikistan"],
  ["TM", "Turkmenistan"],
  ["TN", "Tunisia"],
  ["TO", "Tonga"],
  ["TR", "Turkey"],
  ["TT", "Trinidad and Tobago"],
  ["TV", "Tuvalu"],
  ["TW", "Taiwan"],
  ["TZ", "Tanzania"],
  ["UA", "Ukraine"],
  ["UG", "Uganda"],
  ["US", "United States"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VE", "Venezuela"],
  ["VN", "Vietnam"],
  ["VU", "Vanuatu"],
  ["WS", "Samoa"],
  [
    "cf",
    "Central African countries using CFA Franc"
  ], // ["XAF", "Central African countries using CFA Franc"],
  ["XCD", "East Caribbean countries"], //not working
  [
    "XDR",
    "International Monetary Fund (Special Drawing Rights)"
  ], //not  working
  [
    "bj",
    "West African countries using CFA Franc"
  ], // ["XOF", "West African countries using CFA Franc"],
  ["XPF", "French Polynesia (CFP Franc)"], //not working
  ["YE", "Yemen"],
  ["ZA", "South Africa"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
  ["ZW", "Zimbabwe"],
];
